from ExtracaoConhecimento.Clustering import Clustering 
from ExtracaoConhecimento.SemanticComprehension import SemanticComprehension 
from ExtracaoConhecimento.SentimentAnalysis import SentimentAnalysis 
