from ExtracaoConhecimento.Clustering import Clustering 
from ExtracaoConhecimento.SemanticComprehension import SemanticComprehension 
from ExtracaoConhecimento.EmotionComprehension import EmotionComprehension 
